


@Component
struct  SplashPage{
  build()
  {
    Column(){
      Tabs(){
        TabContent() {
         Image("")
            .width('100%')
            .height('100%')
        }

        TabContent() {
          Image("")
            .width('100%')
            .height('100%')
        }

        TabContent() {
          Image("")
            .width('100%')
            .height('100%')
        }
      }
    }

  }
}